src/users/models.py
from flask.ext.login import AnonymousUserMixin
from src.base.BaseModel import BaseModel
from src.flask_app import db
from src.rooms.models import Room

rooms = db.Table('users_rooms',
                 db.Column('room_id', db.Integer, db.ForeignKey('rooms.id')),
                 db.Column('user_id', db.Integer, db.ForeignKey('users.id'))
                 )


class User(BaseModel):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64))
    email = db.Column(db.String(64), unique=True)
    password = db.Column(db.String(256))
    rooms = db.relationship(Room, secondary=rooms,
                        lazy='dynamic', primaryjoin=(rooms.c.user_id == id),
                        secondaryjoin=(rooms.c.room_id == Room.id),
                        backref=db.backref('users', lazy='dynamic'))

    def in_room(self, room):
        if room in self.rooms:
            return True
        return False

    def add_room(self, room):
        if not self.in_room(room):
            self.rooms.append(room)
            db.session.commit()
            return self

    def delete_room(self, room):
        if self.in_room(room):
            self.rooms.remove(room)
            db.session.commit()
            return self

    def is_authenticated(self):
        if isinstance(self, AnonymousUserMixin):
            return False
        return True

    def is_anonymous(self):
        if isinstance(self, AnonymousUserMixin):
            return True
        return False

    def is_active(self):
        return True

    def get_id(self):
        return unicode(self.id)

    def __repr__(self):
        return 'User %r, rooms: %r' % (self.username, ', '.join(room.title for room in self.rooms))

db.create_all()
db.session.commit()

src/users/forms.py
from wtforms import Form, TextField, PasswordField
from wtforms.fields.html5 import EmailField
from wtforms.validators import Required, Length, EqualTo, ValidationError
from src.users.UserFabric import UserFabric

user_fabric = UserFabric()


class SignInForm(Form):
    email = TextField('email', validators=[Required(message="Email is required"), Length(max=25)], description={'placeholder': 'Email'})
    password = PasswordField('password',
                             validators=[Required(message="Password is required"),
                                         Length(min=4, max=25,
                                                message='Password must contain minimum 4 and maximum 25 symbols')])

    def validate_password(form, field):
        user = user_fabric.get_user_by_email_password(dict(email=form.email.data, password=form.password.data))
        if not user:
            raise ValidationError("There is no such user. Check entered username and password")


class SignUpForm(Form):
    username = TextField('username', validators=[Length(max=25, message='Username must contain less then 25 symbols')],
                         description={'placeholder': 'Username'})
    email = TextField('email', validators=[Required(message="Email is required"), Length(max=25)],
                      description={'placeholder': 'Email'})
    password = PasswordField('password',
                             validators=[Required(message="Password is required"),
                                         EqualTo('password_confirm', message='Passwords must match'),
                                         Length(min=4, max=25,
                                                message='Password must contain minimum 4 and maximum 25 symbols')])
    password_confirm = PasswordField('password_confirm',
                                     validators=[Required(message="Password confirmation is required"),
                                                 Length(min=4, max=25)])


class EmailForm(Form):
    email = EmailField('email', validators=[Required(message="Email is required")])

    def validate_email(form, field):
        user = user_fabric.get_item_by_filters(dict(email=form.email.data))
        if not user:
            raise ValidationError("There is no user with such email. Please, check input")


class ResetPWForm(Form):
    password = PasswordField('password',
                             validators=[Required(message="Password is required"),
                                         EqualTo('password_confirm', message='Passwords must match'),
                                         Length(min=4, max=25,
                                                message='Password must contain minimum 4 and maximum 25 symbols')])
    password_confirm = PasswordField('password_confirm',
                                     validators=[Required(message="Password confirmation is required"),
                                                 Length(min=4, max=25)])

    def validate_password_confirm(form, field):
        if form.password.data != form.password_confirm.data:
            raise ValidationError("Passwords don't match")

src/users/__init__.py
from views import *

src/users/views.py
import base64
import json
from flask import render_template, Blueprint, request, Response, url_for
from flask.ext.login import login_required, logout_user, redirect, login_user, current_user
from src.config import Config
from src.emails.EmailHandler import EmailHandler
from send_email_tasks import send_email
from src.users.forms import SignInForm, SignUpForm, EmailForm, ResetPWForm
from src.users.UserFabric import UserFabric

users = Blueprint('users', __name__, template_folder='templates', static_folder='static',
                  static_url_path='/users/static')
user_fabric = UserFabric()
email_handler = EmailHandler()
ADMINS = Config().ADMINS


@users.route('/')
def index():
    if current_user.username != 'Guest':
        return redirect('/rooms')
    return render_template('index.html')


@users.route('/signin', methods=['GET', 'POST'])
def signin():
    form = SignInForm(request.form)
    if request.method == 'POST' and form.validate():
        user = user_fabric.get_user_by_email_password(form.data)
        if user:
            login_user(user)
            return Response(json.dumps({'result': True}), content_type='application/json')
    return render_template('signin.html', form=form)


@users.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignUpForm(request.form)
    if request.method == 'POST' and form.validate():
        user = user_fabric.create_user(form.data)
        if user:
            login_user(user)
        return Response(json.dumps({'result': True}), content_type='application/json')
    return render_template('signup.html', form=form)


@users.route('/reset/email', methods=['GET', 'POST'])
def reset_email():
    form = EmailForm(request.form)
    if request.method == 'POST' and form.validate():
        user = user_fabric.get_item_by_filters({"email": form.data.get('email', None)})
        url = request.url_root[:-1] + url_for('users.reset',
                                              email_hash=base64.encodestring(form.data.get('email', None)))
        # email_handler.send_email("MiMiChat! | Reset password", ADMINS[0], [form.data.get('email', None)],
        #                          html_text=render_template('reset_password.html', url=url, username=user.username))
        send_email.delay("MiMiChat! | Reset password", ADMINS[0], form.data.get('email', None),
                   html_text=render_template('reset_password.html', url=url, username=user.username))
        return Response(json.dumps(dict(success=True)), content_type='application/json')
    return render_template('reset_email.html', form=form)


@users.route('/reset/<email_hash>', methods=['GET', 'POST'])
def reset(email_hash):
    email = base64.decodestring(email_hash)
    user = user_fabric.get_item_by_filters({"email": email})
    form = ResetPWForm(request.form)
    if request.method == 'POST' and form.validate():
        user_fabric.reset_password(user, form.data.get("password", None))
        login_user(user)
        return Response(json.dumps(dict(success=True)), content_type='application/json')
    return render_template('reset_pw.html', form=form, email_hash=email_hash)


@users.route("/logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    return redirect('/')

src/users/templates/base.html
<head>
    <title>MiMiChat</title>
    <link href="{{ url_for('users.static', filename='css/users.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="icon" href="{{ url_for('rooms.static', filename='img/paw.png') }}" type="image/x-icon">
    <script src="{{ url_for('users.static', filename='js/jquery-2.1.4.min.js') }}" type="text/javascript"></script>

    {% block js_content %}
    {% endblock %}


    {% block css_content %}
    {% endblock %}
</head>
<body>
<div class="navbar">
    <div class="container">
        <ul>

        </ul>
    </div>
</div>
<div class="content-block">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

src/users/templates/index.html
{% extends 'base.html' %}

{% block js_content %}
    <script src="{{ url_for('users.static', filename='js/users.js') }}" type="text/javascript"></script>

{% endblock %}

{% block content %}
    <div class="central-block">
        Nice to see you here!
        <i class="sign-in-button">Sign In</i> or
        <i class="sign-up-button">Sign Up</i>, please!

        <div class="block-for-form"></div>
    </div>
{% endblock %}

src/users/templates/reset_email.html
<form class="user-auth-form" action="{{ url_for('users.reset_email') }}" method="post">
    {{ form.email(placeholder="Email") }}

    {% for error in form.email.errors %}
        <div class="error">{{ error }}</div>
    {% endfor %}

    <input type="button" value="Reset" id="reset-email-button" />
</form>

src/users/templates/reset_pw.html
{% extends 'base.html' %}

{% block js_content %}
    <script src="{{ url_for('users.static', filename='js/users.js') }}" type="text/javascript"></script>

{% endblock %}

{% block content %}
    <div class="central-block">
        <form class="user-auth-form" action="{{ url_for('users.reset_email') }}" method="post">
            {{ form.password(placeholder="Password") }}
            {{ form.password_confirm(placeholder="Confirm password") }}
            {% for error in form.password.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}

            {% for error in form.password_confirm.errors %}
                <div class="error">{{ error }}</div>
            {% endfor %}

            <input type="button" value="Reset" id="reset-pw-button" data-hash="{{ email_hash }}" />
        </form>
    </div>
{% endblock %}

src/users/templates/signin.html
<form class="user-auth-form" action="{{ url_for('users.signin') }}" method="post">
    {{ form.email(placeholder="Email") }}


    {{ form.password(placeholder="Password") }}

    {% for error in form.email.errors %}
        <div class="error">{{ error }}</div>
    {% endfor %}

    {% for error in form.password.errors %}
        <div class="error">{{ error }}</div>
    {% endfor %}
    <div class="forgot-pw-button">Forgot password?</div>
    <input type="button" value="Sign In" id="signin-button"/>
</form>

src/users/templates/signup.html
<form class="user-auth-form" action="{{ url_for('users.signup') }}" method="post">
    {{ form.username(placeholder="Username") }}
    {{ form.email(placeholder="Email") }}


    {{ form.password(placeholder="Password") }}
    {{ form.password_confirm(placeholder="Repeat password") }}

    {% for error in form.username.errors %}
        <div class="error">{{ error }}</div>
    {% endfor %}

    {% for error in form.email.errors %}
        <div class="error">{{ error }}</div>
    {% endfor %}

    {% for error in form.password.errors %}
        <div class="error">{{ error }}</div>
    {% endfor %}
    <input type="button" value="Sign Up" id="signup-button"/>
</form>