src/rooms/models.py
from src.base.BaseModel import BaseModel
from src.flask_app import db


class Room(BaseModel):
    __tablename__ = 'rooms'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64))
    is_private = db.Column(db.Boolean, default=False)


db.create_all()
db.session.commit()

src/rooms/__init__.py
from views import *

src/rooms/views.py
import json
import datetime

from flask import Blueprint, render_template, request, redirect, Response
from flask.ext.login import current_user, login_required
from send_email_tasks import send_email

from src.config import Config
from src.emails.EmailHandler import EmailHandler
from src.rooms.RoomsFabric import RoomsFabric
from src.rooms.RoomsForm import CreateRoomForm, EmailRoomForm

rooms = Blueprint('rooms', __name__, template_folder='templates', static_folder='static',
                  static_url_path='/rooms/static')
rooms_fabric = RoomsFabric()
email_handler = EmailHandler()
default_room_title = 'Room'
ADMINS = Config().ADMINS


@rooms.route('/rooms', methods=['GET', 'POST'])
@login_required
def room_index():
    rooms = rooms_fabric.get_public_rooms()
    form = CreateRoomForm(request.form)
    if request.method == 'POST' and form.validate():
        room = rooms_fabric.create(form.data) if form.data.get('title', None) else rooms_fabric.create(
            {'title': default_room_title, "is_private": False})
        if room:
            current_user.add_room(room)
            return Response(json.dumps(dict(success=True, room=room.id)), content_type='application/json')

    room_ids = [room.id for room in current_user.rooms]
    messages_data = dict()
    offset = int(request.cookies['offset']) / (-60) if request.cookies.get('offset') else 0
    for room_id in room_ids:
        messages_data[room_id] = rooms_fabric.get_messages_by_room(room_id)
    return render_template('room.html', rooms=rooms, form=form, messages_data=messages_data,
                           room_ids=room_ids, offset=datetime.timedelta(hours=offset))


@rooms.route('/join/room/<room_id>')
@login_required
def room_join(room_id):
    room = rooms_fabric.get_by_id(room_id)
    if room not in current_user.rooms:
        current_user.add_room(room)
    return redirect('/rooms#%s' % room.id)


@rooms.route("/rooms/invite/email", methods=['GET', 'POST'])
def send_invite_email():
    form = EmailRoomForm(request.form)
    if request.method == 'POST' and form.validate():
        link = 'http://' + request.__dict__['environ']['HTTP_HOST'] + '/join/room/%s' % form.data.get('room', None)
        # email_handler.send_email("Join room at MiMiChat!", ADMINS[0], [form.data.get('email', None)],
        #                          html_text=render_template('invite_to_room.html', url=link,
        #                                                    username=current_user.username))
        send_email.delay("Join room at MiMiChat!", ADMINS[0], form.data.get('email', None),
                         html_text=render_template('invite_to_room.html', url=link,
                                                   username=current_user.username))
        return Response(json.dumps(dict(success=True)), content_type='application/json')
    return Response(json.dumps(dict(success=False, errors=form.errors)), content_type='application/json')

src/rooms/templates/room.html
{% extends 'room_base.html' %}
{% block js_room_content %}
    <script type="text/javascript">
        SocketChat.data.rooms.user_id = "{{current_user.id}}";
        SocketChat.data.rooms.user_username = "{{current_user.username}}";
        SocketChat.data.rooms.room_ids = "{{ room_ids }}";
        SocketChat.data.rooms.room_static_url = "{{ url_for('rooms.static', filename='') }}";
        SocketChat.data.rooms.invite_email = "{{ url_for('rooms.send_invite_email') }}";
    var offset = new Date().getTimezoneOffset();
    document.cookie =
 'offset='+ offset + '; path=/'
    </script>
{% endblock %}
{% block chat_space %}
    <div class="rooms-index-block">
        <span>Choose existing room or create new</span>

        <form class="create-room-form" action="{{ url_for('rooms.room_index') }}" method="post">
            {{ form.title }} {{ form.is_private }} <span>private</span>
            {% for error in form.title.errors %}
                <p>{{ error }}</p>
            {% endfor %}
            <input type="button" value="create" class="create-room-button"/>
        </form>
        <div class="new-rooms-block">
            {% for room in rooms %}
                {% if room not in current_user.rooms %}
                    <div class="room-item-block">
                        <div class="join-room-button">
                            <a href="{{ url_for('rooms.room_join', room_id=room.id) }}">Join {{ room.title }}</a>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

    </div>
    {% for room in current_user.rooms %}
        <div class="main-chat-block" data-room="{{ room.id }}">
            <div class="members-block" data-room="{{ room.id }}"></div>
            <div id="messages" class="messages" data-room="{{ room.id }}">
            {% if room.is_private %}
                <div class="invite-button" data-room="{{ room.id }}">Invite to Room</div>
                <div class="invite-block" data-room="{{ room.id }}">
                    <form>
                        <input type="email" id="email" class="email" data-room="{{ room.id }}" placeholder="Enter friend's email"/>
                        <div class="errors" data-room="{{ room.id }}"></div>
                        <div class="invite-send-button">Send</div>
                    </form>
                </div>
            {% endif %}
                {% for message in messages_data.get(room.id) %}
                    <div class="message-item">
                        <div class="message-title-block">
                            <span class="message-user-block">{{ message.user.username }}</span> |
                            <span class="message-time-block">{{ (message.created_date + offset).strftime('%d-%m-%y %H:%M ') }}</span>
                        </div>
                        <div class="message-content-block">{{ message.text|safe }}</div>
                    </div>
                {% endfor %}
            </div>
            <div class="message-control-panel" data-room="{{ room.id }}">
                <div class="message-smiles-block" data-room="{{ room.id }}">
                    <div class="smile-row">
                        <img data-smile="(1)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (1).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(2)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (2).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(3)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (3).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(4)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (4).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(5)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (5).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(6)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (6).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(7)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (7).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(8)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (8).png') }}"
                             data-room="{{ room.id }}"/>
                    </div>
                    <div class="smile-row">
                        <img data-smile="(9)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (9).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(10)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (10).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(11)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (11).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(12)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (12).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(13)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (13).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(14)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (14).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(15)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (15).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(16)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (16).png') }}"
                             data-room="{{ room.id }}"/>
                    </div>
                    <div class="smile-row">
                        <img data-smile="(17)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (17).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(18)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (18).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(19)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (19).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(20)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (20).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(21)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (21).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(22)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (22).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(23)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (23).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(24)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (24).png') }}"
                             data-room="{{ room.id }}"/>
                    </div>
                    <div class="smile-row">
                        <img data-smile="(25)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (25).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(26)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (26).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(27)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (27).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(28)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (28).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(29)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (29).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(30)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (30).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(31)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (31).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(32)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (32).png') }}"
                             data-room="{{ room.id }}"/>
                    </div>
                    <div class="smile-row">
                        <img data-smile="(33)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (33).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(34)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (34).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(35)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (35).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(36)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (36).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(37)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (37).png') }}"
                             data-room="{{ room.id }}"/>
                        <img data-smile="(38)"
                             src="{{ url_for('rooms.static', filename='img/emotions/64x64/64 (38).png') }}"
                             data-room="{{ room.id }}"/>

                    </div>
                </div>
                <div id="id_text" class="enter-text-block" contenteditable="true" data-room="{{ room.id }}"></div>

                <div id="open-smiles" data-room="{{ room.id }}"><i class="fa fa-smile-o"></i></div>
                <div id="send_message" data-room="{{ room.id }}"><i class="fa fa-paper-plane-o"></i></div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

src/rooms/templates/room_base.html
{% extends 'base.html' %}
{% block css_content %}
    <link href="{{ url_for('rooms.static', filename='css/room.css') }}" rel="stylesheet"/>
{% endblock %}
{% block js_content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="{{ url_for('rooms.static', filename='js/rooms.js') }}"></script>
    {% block js_room_content %}
    {% endblock %}
{% endblock %}

{% block content %}
    <div class="window-block">

        <div class="rooms-list-block">
            <div class="username-block">
                <a href="{{ url_for('rooms.room_index') }}">{{ current_user.username }}</a>
            </div>

            {% for room in current_user.rooms %}
                <div class="room-item-block" data-room="{{ room.id }}">{{ room.title }}</div>
            {% endfor %}
        </div>
        <div class="chat-room-block">
            <a class="logout-button" href="{{ url_for('users.logout') }}">
                Log Out
            </a>
            {% block chat_space %}
            {% endblock %}
        </div>
    </div>
{% endblock %}